analyzer:
  errors:
    library_private_types_in_public_api: ignore
    file_names: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_dynamic_calls: false
    prefer_single_quotes: true
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
